name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            configure_preset: config-vs2022-ci
            build_preset: build-vs2022-ci
            test_preset: test-vs2022-ci
          - os: ubuntu-latest
            configure_preset: config-gcc-ci
            build_preset: build-gcc-ci
            test_preset: test-gcc-ci
          - os: ubuntu-latest
            configure_preset: config-clang-ci
            build_preset: build-clang-ci
            test_preset: test-clang-ci

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM and Clang
      if: contains(matrix.configure_preset, 'clang')
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18"
        env: true
        cached: true

    - name: Install Ninja (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y ninja-build

    - name: Configure CMake
      run: >
        cmake --preset ${{ matrix.configure_preset }}
        ${{ contains(matrix.configure_preset, 'clang') && '-DCMAKE_CXX_FLAGS=-fuse-ld=lld' || '' }}

    - name: Build
      run: cmake --build --preset ${{ matrix.build_preset }}

    - name: Test
      run: ctest --preset ${{ matrix.test_preset }} -j8 --output-on-failure

  sanitizers:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ASan
            configure_preset: config-clang-ci-asan
            build_preset: build-clang-ci-asan
            test_preset: test-clang-ci-asan
          - name: TSan
            configure_preset: config-clang-ci-tsan
            build_preset: build-clang-ci-tsan
            test_preset: test-clang-ci-tsan

    name: Clang Debug ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18"
        env: true
        cached: true

    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    - name: Configure CMake
      run: cmake --preset ${{ matrix.configure_preset }}

    - name: Build
      run: cmake --build --preset ${{ matrix.build_preset }}

    - name: Test
      run: ctest --preset ${{ matrix.test_preset }} -j8 --output-on-failure
